### ISSUE TITLE
How do I run the GRPC Server?

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/XpringKit#62]
This sdk is confusing to say the least... 

As a developer I would expect the same access to the ledger that is given over the api through web sockets or rpc. I'm under the impression this is not the case with grpc and I need to run my own adaptor over my local server to interact. Is that correct?

**Comment by dangell7** [comment]
If that is correct, why don't I, as a developer, have access to that?

**Comment by keefertaylor** [comment]
I'm sorry that you're feeling confused. I think you may be trying to use features of the XRP Ledger that this SDK doesn't yet support. As far as gRPC, you shouldn't really need to worry about the networking aspects of the SDK, as this is abstracted away from you as a developer (which is one of the points of having an SDK). Instead, you can just call native methods on the SDK.

In specific regards to missing features: This SDK is in early days and doesn't support every feature of the XRP ledger. It supports some common features and will add more over time. The features supported are available in the README. If there's something you're interested in, feel free to open an issue (as you've been doing) so that we know there's demand. 

As far as your networking questions:  [gRPC](https://grpc.io) is a networking technology that this SDK uses to connect to XRP nodes. Note that gRPC is internally encapsulated in this SDK and you don't touch it as a user.

In response to specific questions: 

> As a developer I would expect the same access to the ledger that is given over the api through web sockets or rpc. 
Xpring SDK is aimed at making common features (payments, balances, wallet creation, etc) of the XRP ledger easier to work with for developers. If you'd like the full capabilities of working with raw API calls to rippled's API, you're better off just writing your own requests. 

> I'm under the impression this is not the case with grpc and I need to run my own adaptor over my local server to interact. Is that correct?

gRPC is just a network protocol which connects to a remote service to make RPCs. 

Right now, the remote service is a shim layer which wraps around a rippled node. Conceptually this looks like
```
XpringKit <---grpc---> gRPC Shim <---> rippled node
```

At the moment, Xpring hosts this shim layer on testnet as a convenience. In the future, [rippled nodes will provide a native gRPC interface](https://github.com/ripple/rippled/pull/3159). 

> If that is correct, why don't I, as a developer, have access to that?
Xpring has decided that we'd rather focus on getting an implementation in rippled as a way for developers to self host, as opposed to open sourcing and supporting a shim layer. 

----

Thanks for the feedback and let me know if I can elaborate on anything that may still be confusing.

**Comment by dangell7** [comment]
I guess I'm just upset as I thought this was much farther along with the official announcement and all. I guess I'll wait. If you want to know what common features are required for a wallet application to send and receive payments. I'll list them here for my specific use case. 1. Wallet Creation, Backup, Restore. 2. Balance (Websocket and single call) 3. Transaction List 4. a way for the application to set a specific ID to tract application specific transactions. aka Invoice ID. 5. Escrow 6. Smart Contracts (this WAS a must for me but decided to work around it)

**Comment by dangell7** [comment]
Also, I understand the idea here, its just that I came here expecting an sdk. Instead at every issue I'm pointed to using my own implementation. Which makes me wonder why I would use this anyways if I have to setup 3 of the 5 features on my own. I hope that makes sense.

**Comment by dangell7** [comment]
I think you should focus less on making it easier and more on making it "work". Adding the functionality that already exists in the ledger, then making it easier as an end developer. This has actually made it more difficult as I have to implement both this sdk and my own implementations now. Not only that but I've had to learn the grpc methods. I had to clone the swift repo to work with Firestore. I had to clone this repo to the most recent version of swift. Etc.

**Comment by dangell7** [comment]
If I add the invoiceID to the transaction class in this repo and in the protofs, do I also need to add the invoiceID to the grpc shim in the ripple repo?
